// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9abPAVoUhQViami30FTZXIyAbMVUty9c',
    appId: '1:523614552922:web:26145128e9f816dcdf6963',
    messagingSenderId: '523614552922',
    projectId: 'my-ocd-project',
    authDomain: 'my-ocd-project.firebaseapp.com',
    storageBucket: 'my-ocd-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDOCheyh9FscJYCFwNH3PnLkyyb0XZvO0',
    appId: '1:523614552922:android:951fe9a916e5ed90df6963',
    messagingSenderId: '523614552922',
    projectId: 'my-ocd-project',
    storageBucket: 'my-ocd-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcWrSn3qUV_sTR9SHRRtElzLVChLcJuqI',
    appId: '1:523614552922:ios:1889e4e5fd74f762df6963',
    messagingSenderId: '523614552922',
    projectId: 'my-ocd-project',
    storageBucket: 'my-ocd-project.appspot.com',
    iosClientId: '523614552922-upuf8sa2pmdnauvktc37oq3v0dea7t11.apps.googleusercontent.com',
    iosBundleId: 'com.ocd.ocd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcWrSn3qUV_sTR9SHRRtElzLVChLcJuqI',
    appId: '1:523614552922:ios:1889e4e5fd74f762df6963',
    messagingSenderId: '523614552922',
    projectId: 'my-ocd-project',
    storageBucket: 'my-ocd-project.appspot.com',
    iosClientId: '523614552922-upuf8sa2pmdnauvktc37oq3v0dea7t11.apps.googleusercontent.com',
    iosBundleId: 'com.ocd.ocd',
  );
}
